frameworkVersion: "3"

service: slack-ascii-emoticons

plugins:
  - serverless-aws-documentation
  - serverless-plugin-typescript
  - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

custom:
  documentation: null

functions:
  default:
    handler: src/handler.default
    memorySize: 128
    events:
      - http:
          path: /webhook
          method: post
          request:
            parameters:
              headers:
                X-Slack-Signature: true
                X-Slack-Request-Timestamp: true
          reqValidatorName: SlackRequestValidator
    environment:
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
      SLACK_OAUTH_ACCESS_TOKEN: ${env:SLACK_OAUTH_ACCESS_TOKEN}

resources:
  Resources:
    SlackRequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true
